Simplify base-branch checking
The action has been broken for a while, and this provides a better
message

diff --git a/.github/workflows/base-branch.yml b/.github/workflows/base-branch.yml
--- a/.github/workflows/base-branch.yml
+++ b/.github/workflows/base-branch.yml
@@ -10,9 +10,8 @@ jobs:
   check-base-branch:
     runs-on: ubuntu-latest
     steps:
-      - uses: wpilibsuite/check-base-branch-action@v1.1
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          protected-branches: stable
-          default-branch: main
-          update-branch: true
+      - name: Base Branch
+        run: | 
+          echo "::error ::Base branch of PR is stable. It should be main. Please retarget the base branch of the PR." 
+          exit 1
+
